export const unitSystem_US = {
    "group_altitude"   : "foot",
    "group_amp"        : "amp",
    "group_count"      : "count",
    "group_data"       : "byte",
    "group_degree_day" : "degree_F_day",
    "group_deltatime"  : "second",
    "group_direction"  : "degree_compass",
    "group_distance"   : "mile",
    "group_elapsed"    : "second",
    "group_energy"     : "watt_hour",
    "group_interval"   : "minute",
    "group_length"     : "inch",
    "group_moisture"   : "centibar",
    "group_percent"    : "percent",
    "group_power"      : "watt",
    "group_pressure"   : "inHg",
    "group_radiation"  : "watt_per_meter_squared",
    "group_rain"       : "inch",
    "group_rainrate"   : "inch_per_hour",
    "group_speed"      : "mile_per_hour",
    "group_speed2"     : "mile_per_hour2",
    "group_temperature": "degree_F",
    "group_time"       : "unix_epoch",
    "group_uv"         : "uv_index",
    "group_volt"       : "volt",
    "group_volume"     : "gallon"
};

export const unitSystem_Metric = {
    "group_altitude"   : "meter",
    "group_amp"        : "amp",
    "group_count"      : "count",
    "group_data"       : "byte",
    "group_degree_day" : "degree_C_day",
    "group_deltatime"  : "second",
    "group_direction"  : "degree_compass",
    "group_distance"   : "km",
    "group_elapsed"    : "second",
    "group_energy"     : "watt_hour",
    "group_interval"   : "minute",
    "group_length"     : "cm",
    "group_moisture"   : "centibar",
    "group_percent"    : "percent",
    "group_power"      : "watt",
    "group_pressure"   : "mbar",
    "group_radiation"  : "watt_per_meter_squared",
    "group_rain"       : "cm",
    "group_rainrate"   : "cm_per_hour",
    "group_speed"      : "km_per_hour",
    "group_speed2"     : "km_per_hour2",
    "group_temperature": "degree_C",
    "group_time"       : "unix_epoch",
    "group_uv"         : "uv_index",
    "group_volt"       : "volt",
    "group_volume"     : "litre"
};

export const unitSystem_MetricWX = {
    ...unitSystem_Metric,
    "group_rain"    : "mm",
    "group_rainrate": "mm_per_hour",
    "group_speed"   : "meter_per_second",
    "group_speed2"  : "meter_per_second2"
};

export const obsLabels_en = {
    "altimeter_pressure"     : "Altimeter",
    "console_voltage"        : "Console Voltage",
    "dewpoint_temp"          : "Dewpoint",
    "extra1_humidity"        : "Extra Humidity 1",
    "extra1_temp"            : "Extra Temperature 1",
    "extra2_humidity"        : "Extra Humidity 2",
    "extra2_temp"            : "Extra Temperature 2",
    "extra3_temp"            : "Extra Temperature 3",
    "gauge_pressure"         : "Gauge pressure",
    "heatindex_temp"         : "Heat Index",
    "in_humidity"            : "Inside Humidity",
    "in_temp"                : "Inside temperature",
    "in_temp_battery_status" : "Inside Temperature Battery Status",
    "leaf1_temp"             : "Leaf Temperature 1",
    "leaf2_temp"             : "Leaf Temperature 2",
    "out_humidity"           : "Outside Humidity",
    "out_temp"               : "Outside Temperature",
    "out_temp_battery_status": "Outside Temperature Battery Status",
    "radiation_radiation"    : "Solar radiation",
    "rain_battery_status"    : "Rain Sensor Battery Status",
    "rain_rain"              : "Rain",
    "sealevel_pressure"      : "Sea-level pressure",
    "soil1_temp"             : "Soil Temperature 1",
    "soil2_temp"             : "Soil Temperature 2",
    "soil3_temp"             : "Soil Temperature 3",
    "soil4_temp"             : "Soil Temperature 4",
    "unit_system"            : "Unit System",
    "uv_uv"                  : "UV Index",
    "wind_dir"               : "Wind Direction",
    "wind_speed"             : "Wind Speed",
    "windchill_temp"         : "Windchill",
    "x_wind_speed"           : "E-W Wind Speed",
    "y_wind_speed"           : "N-S Wind Speed",
};

// Could change for other languages:
export const obsLabels = obsLabels_en;

export const unitLabels = {
    "amp"                   : " amp",
    "bit"                   : " b",
    "byte"                  : " B",
    "centibar"              : " cb",
    "cm"                    : " cm",
    "cm_per_hour"           : " cm/hr",
    "cubic_foot"            : " ft\u00b3",
    "day"                   : [" day", " days"],
    "degree_C"              : "\u00b0C",
    "degree_C_day"          : "\u00b0C-day",
    "degree_E"              : "\u00b0E",
    "degree_F"              : "\u00b0F",
    "degree_F_day"          : "\u00b0F-day",
    "degree_compass"        : "\u00b0",
    "foot"                  : " feet",
    "gallon"                : " gal",
    "hPa"                   : " hPa",
    "inHg"                  : " inHg",
    "hour"                  : [" hour", " hours"],
    "inch"                  : " in",
    "inch_per_hour"         : " in/hr",
    "km"                    : " km",
    "km_per_hour"           : " kph",
    "km_per_hour2"          : " kph",
    "knot"                  : " knots",
    "knot2"                 : " knots",
    "litre"                 : " l",
    "mbar"                  : " mbar",
    "meter"                 : " meters",
    "meter_per_second"      : " m/s",
    "meter_per_second2"     : " m/s",
    "mile"                  : " mile",
    "mile_per_hour"         : " mph",
    "mile_per_hour2"        : " mph",
    "minute"                : [" minute", " minutes"],
    "mm"                    : " mm",
    "mmHg"                  : " mmHg",
    "mm_per_hour"           : " mm/hr",
    "percent"               : "%",
    "second"                : [" second", " seconds"],
    "uv_index"              : "",
    "volt"                  : " V",
    "watt"                  : " W",
    "watt_hour"             : " Wh",
    "watt_per_meter_squared": " W/m\u00b2",
    "NONE"                  : ""
};

// This uses formatting supplied by sprintf-js.
// This is essentially identical to sprintf and python formatting.
// See https://github.com/alexei/sprintf.js
export const unitFormats = {
    "amp"                   : "%.1f",
    "bit"                   : "%.0f",
    "byte"                  : "%.0f",
    "centibar"              : "%.0f",
    "cm"                    : "%.2f",
    "cm_per_hour"           : "%.2f",
    "cubic_foot"            : "%.1f",
    "day"                   : "%.1f",
    "degree_C"              : "%.1f",
    "degree_C_day"          : "%.1f",
    "degree_E"              : "%.1f",
    "degree_F"              : "%.1f",
    "degree_F_day"          : "%.1f",
    "degree_compass"        : "%.0f",
    "foot"                  : "%.0f",
    "gallon"                : "%.1f",
    "hPa"                   : "%.1f",
    "hour"                  : "%.1f",
    "inHg"                  : "%.3f",
    "inch"                  : "%.2f",
    "inch_per_hour"         : "%.2f",
    "km"                    : "%.1f",
    "km_per_hour"           : "%.0f",
    "km_per_hour2"          : "%.1f",
    "knot"                  : "%.0f",
    "knot2"                 : "%.1f",
    "litre"                 : "%.1f",
    "mbar"                  : "%.1f",
    "meter"                 : "%.0f",
    "meter_per_second"      : "%.0f",
    "meter_per_second2"     : "%.1f",
    "mile"                  : "%.1f",
    "mile_per_hour"         : "%.0f",
    "mile_per_hour2"        : "%.1f",
    "mm"                    : "%.1f",
    "mmHg"                  : "%.1f",
    "mm_per_hour"           : "%.1f",
    "percent"               : "%.0f",
    "second"                : "%.0f",
    "uv_index"              : "%.1f",
    "volt"                  : "%.1f",
    "watt"                  : "%.1f",
    "watt_hour"             : "%.1f",
    "watt_per_meter_squared": "%.0f",
    "NONE"                  : "   N/A"
};